api/urls.py
from django.urls import path 
from .views import (
    StaffListCreateAPIView, 
    StaffDetailAPIView, 
    StaffDestroyAPIView, 
    InventoryListCreateAPIView, 
    InventoryDetailAPIView, 
    InventoryDestroyAPIView, 
    SaleListCreateAPIView, 
    SaleDetailAPIView, 
    SaleDestroyAPIView, 
    JobListCreateAPIView, 
    JobDetailAPIView, 
    JobDestroyAPIView, 
    InventoryTypeListCreateAPIView, 
    InventoryTypeDetailAPIView, 
    InventoryTypeDestroyAPIView
)

app_name = 'api'
urlpatterns = [
    path('staff_list/', StaffListCreateAPIView.as_view()), 
    path('staff_detail/<int:pk>/', StaffDetailAPIView.as_view()), 
    path('staff_delete/<int:pk>/', StaffDestroyAPIView.as_view()), 

    path('inventory_list/', InventoryListCreateAPIView.as_view()), 
    path('inventory_detail/<int:pk>/', InventoryDetailAPIView.as_view()), 
    path('inventory_delete/<int:pk>/', InventoryDestroyAPIView.as_view()), 

    path('sale_list/', SaleListCreateAPIView.as_view()), 
    path('sale_detail/<int:pk>/', SaleDetailAPIView.as_view()), 
    path('sale_delete/<int:pk>/', SaleDestroyAPIView.as_view()), 
    
    path('job_list/', JobListCreateAPIView.as_view()), 
    path('job_detail/<int:pk>/', JobDetailAPIView.as_view()), 
    path('job_delete/<int:pk>/', JobDestroyAPIView.as_view()), 

    path('inv_type_list/', InventoryTypeListCreateAPIView.as_view()), 
    path('inv_type_detail/<int:pk>/', InventoryTypeDetailAPIView.as_view()), 
    path('inv_type_delete/<int:pk>/', InventoryTypeDestroyAPIView.as_view()), 

]

core/urls.py
from django.urls import path 
from django.conf import settings 
from django.conf.urls.static import static 
from .views import (
    homeView,
    reportView, 
    filterView, 
    reminderCreateView, 
    reminderHandleView, 
    helpView, 
)

app_name = 'core'
urlpatterns = [
    path('', homeView, name='home'), 
    path('report/', reportView, name='report'), 
    path('filter/', filterView, name='filter'), 
    path('reminders/', reminderCreateView, name='reminder'), 
    path('reminder-handle/', reminderHandleView, name='reminder-handle'), 
    path('help/', helpView, name='help'), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/urls.py
from django.urls import path 
from django.conf import settings 
from django.conf.urls.static import static 

from .views import (
    jobCreateView, 
    JobDeleteView, 
    JobDetailView, 
    JobListView, 
    JobUpdateView
)

app_name = 'job'
urlpatterns = [
    path('list/', JobListView.as_view(), name='job-list'), 
    path('<int:id>/', JobDetailView.as_view(), name='job-detail'), 
    path('<int:id>/delete/', JobDeleteView.as_view(), name='job-delete'), 
    path('create/', jobCreateView, name='job-create'), 
    path('<int:id>/update/', JobUpdateView.as_view(), name='job-update'),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

legend/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')), 
    path('core/', include('core.urls')), 
    path('staff/', include('staff.urls')), 
    path('inventory/', include('inventory.urls')), 
    path('job/', include('job.urls')), 
    path('sale/', include('sale.urls')), 
]

sale/urls.py
from django.urls import path 
from .views import (
    # SaleCreateView, 
    SaleDetailView, 
    SaleConfirmDeleteView, 
    SaleListView, 
    saleDelete, 
    saleCreateView, 
    saleDetailView, 
    saleUpdateView
)

app_name = 'sale'
urlpatterns = [
    path('list/', SaleListView.as_view(), name='sale-list'), 
    # path('<int:id>/', SaleDetailView.as_view(), name='sale-detail'),
    path('<int:id>/', saleDetailView, name='sale-detail'), 
    path('<int:id>delete/', saleDelete, name='sale-delete'), 
    path('<int:id>/confirm_delete/', SaleConfirmDeleteView.as_view(), name='sale-confirm-delete'), 
    # path('create/', SaleCreateView.as_view(), name='sale-create'), 
    path('create/', saleCreateView, name='sale-create'), 
    path('<int:id>/update/', saleUpdateView, name='sale-update')
]

staff/urls.py
from django.urls import path 
from django.conf import settings 
from django.conf.urls.static import static 
from .views import (
    staffCreateView, 
    StaffDeleteView, 
    StaffDetailView, 
    StaffListView, 
    StaffUpdateView,
    staffListView, 
)

app_name = 'staff'
urlpatterns = [
    path('list/', StaffListView.as_view(), name='staff-list'), 
    path('<int:pk>/', StaffDetailView.as_view(), name='staff-detail'), 
    # path('create/', StaffCreateView.as_view(), name='staff-create'), 
    path('create/', staffCreateView, name='staff-create'), 
    path('<int:pk>/update/', StaffUpdateView.as_view(), name='staff-update'), 
    path('<int:pk>/delete/', StaffDeleteView.as_view(), name='staff-delete')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/models.py
from django.db import models
from staff.models import Staff 
from inventory.models import Inventory 

# Create your models here.
class Job(models.Model):
    status_options = [
        ('Completed', 'completed'), 
        ('Incompleted', 'incompleted'), 
        ('Cancelled', 'cancelled'), 
        ('Postponed', 'postponed')
    ]
    staff_assigned = models.CharField(max_length=300, blank=False, null=False, default='')
    date = models.DateField(auto_now=False, default=None) 
    location = models.CharField(max_length=200, blank=False, null=False) 
    inventory_used = models.CharField(max_length=300, blank=True) 
    prices = models.CharField(max_length=200, blank=True)
    quantities = models.CharField(max_length=100, blank=True)
    battery_serials = models.CharField(max_length=400, default='{}', blank=True, null=True)
    inverter_serials = models.CharField(max_length=300, default='{}', blank=True, null=True) 
    other_items = models.CharField(max_length=500, blank=True, null=True) 
    other_items_expenses = models.CharField(max_length=500, blank=True, null=True) 
    transportation_cost = models.DecimalField(max_digits=20, decimal_places=2, default=0.00)
    total_expenses = models.DecimalField(max_digits=20, decimal_places=2, default=0.00) 
    job_status = models.CharField(choices=status_options, max_length=20, default='Completed')
    job_description = models.TextField(blank=True, null=True) 
    customer_charge = models.DecimalField(max_digits=20, decimal_places=2, default=0.00) 
    customer_name = models.CharField(max_length=50, blank=True) 
    customer_phone = models.CharField(max_length=20, blank=True) 
    remark = models.TextField(blank=True, null=True) 

    has_refill_reminder = models.BooleanField(default=False) 
    has_maintenance_reminder = models.BooleanField(default=False) 
    battery_serials_done = models.CharField(max_length=400, default='', blank=True, null=True)
    inverter_serials_done = models.CharField(max_length=300, default='', blank=True, null=True) 

    def __str__(self):
        return str(self.date) 

job/views.py
from django.shortcuts import render, redirect 
from django.views import View
from django.views.generic import (
    CreateView, 
    DetailView, 
    ListView, 
    UpdateView, 
    DeleteView
)
from .models import Job 
# from .forms import JobCreateForm
from staff.models import Staff
from datetime import date as theDate
from inventory.models import Inventory 

ALL_STAFF = Staff.objects.all() 
ALL_INVENTORY = Inventory.objects.filter(deactivate=False) 
ALL_STATUSES = ['Completed', 'Cancelled', 'Incompleted', 'Postponed']

# Create your views here
class JobListView(ListView):
    queryset = Job.objects.all().order_by('-date')# .reverse() 
    template_name = 'job/job_list.html' 
    # print(queryset) 

def listify(obj_string, obj_type): 
    obj_list = []
    if obj_string: 
        for obj_string_item in obj_string.split(','):
            if obj_string_item: 
                obj_list.append(obj_type(obj_string_item))
    return obj_list
    

class JobDetailView(DetailView):
    qqeryset = Job.objects.all() 
    template_name = 'job/job_detail.html' 

    def get_object(self): 
        pk_ = self.kwargs.get('id') 
        obj = Job.objects.get(id=pk_)
        return obj 

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        obj = context['object'] 

        all_job_inv = listify(obj.inventory_used, str)
        all_job_prices = listify(obj.prices, float) 
        all_job_quantities = listify(obj.quantities, int) 
        if (len(all_job_inv) == len(all_job_prices)) and (len(all_job_prices) == (len(all_job_quantities))):
            zipped_details1 = zip(all_job_inv, all_job_prices, all_job_quantities)
            context['zipped1'] = zipped_details1

        other_items, other_costs= listify(obj.other_items, str), listify(obj.other_items_expenses, float)
        if len(other_items) == len(other_costs):
            zipped_details2 = zip(other_items, other_costs)
            context['zipped2'] = zipped_details2

        context['all_staff'] = listify(obj.staff_assigned, str)
        context['battery_serials'] = eval(obj.battery_serials) 
        context['inverter_serials'] = eval(obj.inverter_serials)
        # print(context) 
        return context 


def jobCreateView(request):
    '''I used a FBV instead of a CBV because I had to manually convert 
    some of the form data into models before saving the inventory object
    Update: It's actually because I didn't know how to use CBVs
    ''' 
    template_name = 'job/job_create.html'
    # battery_inv = [good for good in ALL_INVENTORY if 'battery' in good.name.lower()]
    # inverter_inv = [good for good in ALL_INVENTORY if 'inverter' in good.name.lower() ]
    battery_inv = ALL_INVENTORY.filter(type__name='Battery') 
    inverter_inv = ALL_INVENTORY.filter(type__name='Inverter')


    if request.method == 'POST':
        form = request.POST 
        ''' 
        GET FORM DATA 
        '''
        # GET STAFF ASSIGNED
        data = {}
        staff_string = ''
        for staff in ALL_STAFF: 
            try:
                if form[staff.name]:
                    staff_string += staff.name + ','
            except KeyError: 
                continue
        staff_string = staff_string.strip(',') 
        data['staff_assigned'] = staff_string

        # print(goods, prices, quantities)
        data['location'] = form['location']
        if data['location']:
            data['location'] = data['location'].lower()
        data['transportation_cost'] = form['transportation_cost'] 
        data['job_description'] = form['job_description']
        ######################################
        ''' 
        Re-render create page with error message if no transport cost and job description 
        '''
        required = [
            data['staff_assigned'],     
            data['transportation_cost'], 
            data['job_description'], 
            data['location']
        ]
        if ('' in required): #  or (0.00 in required):
            some_error = "Please enter the staff assigned, transportation cost, location and nature of the job"
            context = {
                'all_staff': ALL_STAFF , 
                'all_inventory': ALL_INVENTORY,
                'all_job_statuses': ALL_STATUSES,
                'some_error': some_error,
            }
            return render(request, template_name, context)
        ###################################################
        ''' Extract the goods, prices, and quantities from the form data '''
        # GET INVENTORY USED 
        goods = '' 
        prices = '' 
        quantities = ''
        for inv in ALL_INVENTORY:
            try: 
                good_ = form[inv.name]
                price_ = form[inv.name + '_price']
                quantity_ = form[inv.name + '_quantity']

                if good_ and float(price_) and int(quantity_):
                    goods += inv.name + ','  
                    prices += price_ + ','
                    quantities += quantity_ + ','
                    
            except (KeyError, TypeError, ValueError): 
                continue 

        data['inventory_used'] = goods.strip(',') 
        data['quantities'] = quantities.strip(',') 
        data['prices'] = prices.strip(',') 

        # EXTRACT SERIAL NUMBERS 
        bat_serials = {} 
        for bat in battery_inv: # bat is an inventory 
            # print('Bat name', bat.name)
            val = form.get(f'{bat.name}_serials')
            if val: 
                bat_serials[bat.name] = val
        battery_serials = repr(bat_serials) 

        invt_serials = {}
        for invt in inverter_inv: 
            # print('Invt name', invt.name)
            val = form.get(f'{invt.name}_serials')
            if val: 
                invt_serials[invt.name] = val 
        inverter_serials = repr(invt_serials) 

        data['battery_serials'] = battery_serials 
        data['inverter_serials'] = inverter_serials

        # OTHER DATA 
        data['date'] = form['date'] if form['date'] else theDate.today()
        data['other_items'] = form['other_items']  
        data['other_items_expenses'] = form['other_items_costs'] 
        data['job_status'] = form['job_status'] 
        data['customer_name']= form['customer_name']  
        data['customer_phone'] = form['customer_phone'] 
        data['customer_charge'] = form['customer_charge']  if form['customer_charge']  else 0.00
        data['remark'] = form['remark'] 

        # CALCULATE TOTAL SPENT 
        total = 0.00 
        prices_, quantities_ = listify(data['prices'], float), listify(data['quantities'], int) 
        for i, j in zip(prices_, quantities_): 
            # print('for total', i, j, i*j)
            total += i * j
        other_items_costs_ = listify(data['other_items_expenses'], float)
        for i in other_items_costs_: 
            # print('for total:', i)
            total += i
        total += float(data['transportation_cost'])
        data['total_expenses'] = total 

        ##################################################
        # UPDATE INVENTORY 
        job_inv_list = listify(data['inventory_used'], str)
        job_quan_list = listify(data['quantities'], int) 
        for inv in ALL_INVENTORY:
            # # print(inv.name)
            if inv.name in job_inv_list:
                ind = job_inv_list.index(inv.name) 
                # # print(ind)
                quan = job_quan_list[ind]
                # print('updating inventory', data['quantities'], ind, quan) 
                inv.quantity -= quan
                inv.save()
        ##############################################3

        # CREATE JOB INSTANCE 
        instance = Job(**data) 
        instance.save()
        # print(instance) 
        return redirect('../list/') 
        
    elif request.method == 'GET': 
        # print(ALL_INVENTORY)
        # form = JobCreateForm()
        # print(ALL_STAFF)
        context = {
            'all_staff': Staff.objects.filter(active=True), #ALL_STAFF , 
            'all_inventory': ALL_INVENTORY,
            'all_job_statuses' : ALL_STATUSES,
            'battery_inv': battery_inv, 
            'inverter_inv': inverter_inv,
        }
        return render(request, template_name, context)


class JobUpdateView(View):
    template_name = 'job/job_update.html'
    success_url = '../'

    def get_object(self): 
        pk_ = self.kwargs.get('id') 
        obj = Job.objects.get(id=pk_)
        return obj 

    def get(self, request, *args, **kwargs):
        battery_inv = [good for good in ALL_INVENTORY if 'battery' in good.name.lower()]
        inverter_inv = [good for good in ALL_INVENTORY if 'inverter' in good.name.lower() ]

        # Do not forget *args, **kwargs above 
        object = self.get_object()
        obj_staff = listify(object.staff_assigned, str) 
        obj_inv = listify(object.inventory_used, str) 
        obj_quan = listify(object.quantities, int) 
        quant = []
        for _, inv in enumerate(ALL_INVENTORY):
            if inv.name in obj_inv: 
                ind = obj_inv.index(inv.name)
                quant.append(obj_quan[ind])
            else: quant.append(0)
        zip_inv_quant = zip(ALL_INVENTORY, quant)


        context = {
            'object': object, 
            'all_staff': ALL_STAFF, 
            'all_job_statuses': ALL_STATUSES, 
            'obj_staff': obj_staff, 
            'obj_inv': obj_inv, 
            'obj_date': str(object.date), 
            'zip_inv_quant': zip_inv_quant, 
            'battery_inv': [inv.name for inv in battery_inv], 
            'inverter_inv': [inv.name for inv in inverter_inv], 
            'obj_batt_serials': eval(object.battery_serials), 

job/templates/job/base.html
{% load static %} 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Base{% endblock %}</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <style>
        a, th, .crimson {
            text-decoration: none;
            color: crimson;
        }
        .detail {
            font-size: large;
        }
        .label {
            font-weight: bold;
        }
        .font-table {
            font-size: larger;
        }
        .small {
            font-size: smaller;
        }
        .tiny {
            font-size: x-small;
        }
        .thick {
            font-weight: bold;
        }
        .big-text {
            font-size: x-large;
            }
        .footer>.row>.col>a {
            color: gray;
        }
        .footer>.row>.col>a:hover {
            color: rgb(11, 129, 129);
        }
        a:hover {
            color: darkgreen;
        }
    </style>
</head>
<body>
    {% block content %} 
        Base 
    {% endblock %} 

    <div class="footer">
        <div class="row row-cols-4 my-5 p-3 text-muted bg-dark text-center">
            <div class="col detail">
                <a href="{% url 'core:home' %}">Home</a>
            </div>
            <div class="col detail">
                <a href="{% url 'staff:staff-list' %}">Staff</a>
            </div>
            <div class="col detail">
                <a href="{% url 'inventory:inventory-list' %}">Inventory</a>
            </div>
            <div class="col detail">
                <a href="{% url 'sale:sale-list' %}">Sales</a>
            </div>
            <div class="col detail">
                <a href="{% url 'job:job-list' %}">Jobs</a>
            </div>
            <div class="col detail">
                <a href="{% url 'core:report' %}">Report</a>
            </div>
            <div class="col detail`">
                <a href="{% url 'core:reminder' %}">Reminders</a>
            </div>
            <div class="col detail">
                <a href="{% url 'core:help' %}">Help</a>
            </div>
        </div>
    </div>
</body>
</html>

job/templates/job/job_delete.html
{% extends 'job/base.html' %} 

{% block title %}Delete Job{% endblock %} 

{% block content %} 
<div class="container">
    <div class="row display-4">
        Confirm Delete
    </div>
    <div class="row">
        <p class="detail">Are you sure you want to delete this record?</p>
        <p class="text-primary display-4">{{ object.date }}</p>
        <p class="text-primary display-4">{{ object.job_description }} at {{ object.location|title }}</p>
        <div class="row">
            <div class="col mx-2 btn btn-secondary py-3">
                <a href="{% url 'job:job-detail' object.id %}"><span class="text-white">Cancel</span>
                </a>
            </div>
            <div class="col mx-2 text-white btn btn-danger">
                <form method="post" action="{% url 'job:job-delete' object.id %}">{% csrf_token %}
                    <button type="submit" class="btn btn-danger">Confirm</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %} 

job/templates/job/job_detail.html
{% extends 'job/base.html' %} 
{% load custom_tags %}
{% block title %}Job Detail{% endblock %} 

{% block content %} 

<div class="container">
    <!-- job data  -->
    <div class="row rounded m-2 g-4">
        <div class="row display-2">
            Job carried out on {{ object.date }}
        </div>
        <hr>
        <!-- staff assigned -->
        <div class="row crimson label detail">
            Staff Assigned:
        </div>
        <div class="row row-cols-sm-2 row-cols-lg-3">
            {% for staff in all_staff %}
            <div class="col detail">{{ staff }}</div>
            {% endfor %}
        </div>
        <hr>
        <!-- location -->
        <div class="row crimson label detail">
            Location:
        </div>
        <div class="row detail">
            <div class="col">{{ object.location|title }}</div>
        </div>
        <hr>
        <!-- job description  -->
        <div class="row crimson label detail">
            Description:
        </div>
        <div class="row detail">
            <div class="col">{{ object.job_description }}</div>
        </div>
        <hr>
        <!-- goods -->
        <div class="row detail">
            {% if zipped1 %} 
                <table class="table table-hover">
                    <tr>
                        <th>Good sold</th>
                        <th>Price</th>
                        <th>Quantity</th>
                    </tr>
                    {% for inv, price, quantity in zipped1 %}
                    <tr>
                        <td>
                            {{ inv }}
                        </td>
                        <td>
                            {{ price }}
                        </td>
                        <td>
                            {{ quantity }}
                        </td>
                    </tr>
                    {% endfor %}
                    
                </table>
            {% endif %}

            {% if zipped2 %}
                <table class="table table-hover">
                    <tr>
                        <th>Other Items</th>
                        <th></th>
                        <th>Costs</th>
                    </tr>
                    <tr>
                        <td>Transportation</td>
                        <td></td>
                        <td>{{ object.transportation_cost }}</td>
                    </tr>
                    {% for item, cost in zipped2 %}
                    <tr>
                        <td>
                            {{ item }}
                        </td>
                        <td></td>
                        <td>
                            {{ cost }}
                        </td>
                    </tr>
                    {% endfor %}
                    <tr class="table-success">
                        <th scope="row">Total:</th>
                        <td></td>
                        <td>{{ object.total_expenses }}</td>
                    </tr>
                </table>
            {% else %}
                <table class="table table-hover">
                    <tr class="table-success">
                        <th scope="row">Total:</th>
                        <td></td>
                        <td>{{ object.total_expenses }}</td>
                    </tr>
                </table>
            {% endif %}


        </div>
        <hr>

        <!-- Serial Numbers -->
        <div class="row crimson label detail">
            Battery Serial Numbers:
        </div>
        <div class="row detail">
            {% for batt in battery_serials %}
            {% if battery_serials|get_value:batt %}
                <p><span class="thick">{{ batt }}:</span> {{ battery_serials|get_value:batt }}</p>
            {% endif %}
            {% endfor %}
        </div>
        <hr>

        <div class="row crimson label detail">
            Inverter Serial Numbers:
        </div>
        <div class="row detail">
            {% for invt in inverter_serials %}
            {% if inverter_serials|get_value:invt %}
                <p><span class="thick">{{ invt }}:</span> {{ inverter_serials|get_value:invt }}</p>
            {% endif %}
            {% endfor %}
        </div>
        <!-- fin -->

        <!-- <div class="row crimson label detail">
            Battery Serial Numbers:
        </div>
        <div class="row detail">
            {% for batt in object.battery_serials %}
                <p><span class="thick">{{ batt }}:</span> {{ battery_serials|get_value:batt }}</p>
            {% endfor %}
        </div>
        <hr>

        <div class="row crimson label detail">
            Inverter Serial Numbers:
        </div>
        <div class="row detail">
            {% for invt in inverter_inv %}
                <p><span class="thick">{{ invt }}:</span> {{ inverter_serials|get_value:invt }}</p>
            {% endfor %}
            <div class="col">{{ object.inverter_serials }}</div>
        </div> -->
        <hr>

        <!-- job status  -->
        <div class="row crimson label detail">
            Status:
        </div>
        <div class="row detail">
            <div class="col">{{ object.job_status }}</div>
        </div>
        <hr>
        <!-- customer -->
        <table class="table detail">
            <tr>
                <th>Customer</th>
                <th>Phone</th>
                <th>Fee</th>
            </tr>
            <tr>
                <td>{{ object.customer_name }}</td>
                <td>{{ object.customer_phone }}</td>
                <td>{{ object.customer_charge }}</td>
            </tr>
        </table>
        <div class="row detail">
            <div class="col-auto label crimson">Remark:</div>
            <div class="col detail">{{ object.remark }}</div>
        </div>
    </div>

    <!-- footer buttons  -->
    <hr class="">

    <div class="row">
        <div class="col-3 mx-1 btn btn-primary my-2 text-center py-3">
            <a class="text-white" href="{% url 'job:job-list' %}">Back</a>
        </div>
        <div class="col-3 mx-auto btn btn-primary my-2 text-center py-3">
            <a class="text-white" href="{% url 'job:job-update' object.id %}">Update</a>
        </div>
        <div class="col-3 mx-1 btn btn-danger my-2 text-center py-3">
            <a class="text-white" href="{% url 'job:job-delete' object.id %}">Delete</a>
        </div>
    </div>
</div>

{% endblock %}

job/templates/job/job_list.html
{% extends './base.html' %} 

{% block title %}Job List{% endblock %} 

{% block content %} 
<div class="container">

    <div class="row g-3">
        <div class="col display-1">All Jobs</div>
        <div class="col mt-5"><a class="h4" href="{% url 'job:job-create' %}">Record New Job</a>
        </div>
        <div class="col mt-5"><a class="h4" href="{% url 'core:home' %}">Home</a></div>
    </div>

    <hr>

    <div class="job my-3">
        {% for job in object_list %} 
        <table class="table table-hover">
            <tr class="border border-3 rounded-2 my-2 py-3">
                <td class="display-5">
                    <p><a href="{% url 'job:job-detail' job.id %}">{{ job.date }}</a></p>
                </td>
                <td class="big-text ont-table text-end">
                    {{ job.job_description|title }} at {{ job.location|title }}
                </td>
            </tr>
        </table>
        {% endfor %}
    </div>

</div>

{% endblock %} 