api/urls.py
from django.urls import path 
from .views import (
    StaffListCreateAPIView, 
    StaffDetailAPIView, 
    StaffDestroyAPIView, 
    InventoryListCreateAPIView, 
    InventoryDetailAPIView, 
    InventoryDestroyAPIView, 
    SaleListCreateAPIView, 
    SaleDetailAPIView, 
    SaleDestroyAPIView, 
    JobListCreateAPIView, 
    JobDetailAPIView, 
    JobDestroyAPIView, 
    InventoryTypeListCreateAPIView, 
    InventoryTypeDetailAPIView, 
    InventoryTypeDestroyAPIView
)

app_name = 'api'
urlpatterns = [
    path('staff_list/', StaffListCreateAPIView.as_view()), 
    path('staff_detail/<int:pk>/', StaffDetailAPIView.as_view()), 
    path('staff_delete/<int:pk>/', StaffDestroyAPIView.as_view()), 

    path('inventory_list/', InventoryListCreateAPIView.as_view()), 
    path('inventory_detail/<int:pk>/', InventoryDetailAPIView.as_view()), 
    path('inventory_delete/<int:pk>/', InventoryDestroyAPIView.as_view()), 

    path('sale_list/', SaleListCreateAPIView.as_view()), 
    path('sale_detail/<int:pk>/', SaleDetailAPIView.as_view()), 
    path('sale_delete/<int:pk>/', SaleDestroyAPIView.as_view()), 
    
    path('job_list/', JobListCreateAPIView.as_view()), 
    path('job_detail/<int:pk>/', JobDetailAPIView.as_view()), 
    path('job_delete/<int:pk>/', JobDestroyAPIView.as_view()), 

    path('inv_type_list/', InventoryTypeListCreateAPIView.as_view()), 
    path('inv_type_detail/<int:pk>/', InventoryTypeDetailAPIView.as_view()), 
    path('inv_type_delete/<int:pk>/', InventoryTypeDestroyAPIView.as_view()), 

]

core/urls.py
from django.urls import path 
from django.conf import settings 
from django.conf.urls.static import static 
from .views import (
    homeView,
    reportView, 
    filterView, 
    reminderCreateView, 
    reminderHandleView, 
    helpView, 
)

app_name = 'core'
urlpatterns = [
    path('', homeView, name='home'), 
    path('report/', reportView, name='report'), 
    path('filter/', filterView, name='filter'), 
    path('reminders/', reminderCreateView, name='reminder'), 
    path('reminder-handle/', reminderHandleView, name='reminder-handle'), 
    path('help/', helpView, name='help'), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/urls.py
from django.urls import path 
from django.conf import settings 
from django.conf.urls.static import static 

from .views import (
    jobCreateView, 
    JobDeleteView, 
    JobDetailView, 
    JobListView, 
    JobUpdateView
)

app_name = 'job'
urlpatterns = [
    path('list/', JobListView.as_view(), name='job-list'), 
    path('<int:id>/', JobDetailView.as_view(), name='job-detail'), 
    path('<int:id>/delete/', JobDeleteView.as_view(), name='job-delete'), 
    path('create/', jobCreateView, name='job-create'), 
    path('<int:id>/update/', JobUpdateView.as_view(), name='job-update'),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

legend/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')), 
    path('core/', include('core.urls')), 
    path('staff/', include('staff.urls')), 
    path('inventory/', include('inventory.urls')), 
    path('job/', include('job.urls')), 
    path('sale/', include('sale.urls')), 
]

sale/urls.py
from django.urls import path 
from .views import (
    # SaleCreateView, 
    SaleDetailView, 
    SaleConfirmDeleteView, 
    SaleListView, 
    saleDelete, 
    saleCreateView, 
    saleDetailView, 
    saleUpdateView
)

app_name = 'sale'
urlpatterns = [
    path('list/', SaleListView.as_view(), name='sale-list'), 
    # path('<int:id>/', SaleDetailView.as_view(), name='sale-detail'),
    path('<int:id>/', saleDetailView, name='sale-detail'), 
    path('<int:id>delete/', saleDelete, name='sale-delete'), 
    path('<int:id>/confirm_delete/', SaleConfirmDeleteView.as_view(), name='sale-confirm-delete'), 
    # path('create/', SaleCreateView.as_view(), name='sale-create'), 
    path('create/', saleCreateView, name='sale-create'), 
    path('<int:id>/update/', saleUpdateView, name='sale-update')
]

staff/urls.py
from django.urls import path 
from django.conf import settings 
from django.conf.urls.static import static 
from .views import (
    staffCreateView, 
    StaffDeleteView, 
    StaffDetailView, 
    StaffListView, 
    StaffUpdateView,
    staffListView, 
)

app_name = 'staff'
urlpatterns = [
    path('list/', StaffListView.as_view(), name='staff-list'), 
    path('<int:pk>/', StaffDetailView.as_view(), name='staff-detail'), 
    # path('create/', StaffCreateView.as_view(), name='staff-create'), 
    path('create/', staffCreateView, name='staff-create'), 
    path('<int:pk>/update/', StaffUpdateView.as_view(), name='staff-update'), 
    path('<int:pk>/delete/', StaffDeleteView.as_view(), name='staff-delete')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.utils.timezone import now 

from sale.models import Sale 
from job.models import Job

from datetime import datetime as dt

thisDay = dt.today

class RefillReminder(models.Model):
    # For every sale or job 
    job = models.ForeignKey(Job, on_delete=models.CASCADE, blank=True, null=True) 
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE, blank=True, null=True) 
    alert = models.BooleanField(default=False) 
    last_refill_date = models.DateField(default=thisDay)
    months_passed = models.IntegerField(default=0) 
    forget = models.BooleanField(default=False) 

    def __str__(self):
        return 'RefillReminder' + str(self.id) + ' ' + str(self.last_refill_date)

class WarrantyReminder(models.Model):
    # For every battery or inverter
    serial_no = models.CharField(max_length=20, default='')  # string of dict mapping battery name to serial numbers
    product = models.CharField(max_length=100, default='')
    job = models.ForeignKey(Job, on_delete=models.CASCADE, blank=True, null=True) 
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE, blank=True, null=True) 
    alert = models.BooleanField(default=False) 
    months_passed = models.IntegerField(default=0) 
    is_sale = models.BooleanField(default=True) 
    forget = models.BooleanField(default=False) 

class MaintenanceReminder(models.Model):
    # For every job
    job = models.ForeignKey(Job, on_delete=models.CASCADE, blank=True, null=True) 
    alert = models.BooleanField(default=False) 
    last_maintenance_date = models.DateField(default=thisDay) 
    months_passed = models.IntegerField(default=0) 
    forget = models.BooleanField(default=False)

    def __str__(self):
        return 'MaintenanceReminder' + str(self.id) + ' ' + str(self.last_maintenance_date)

core/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import FieldError
from django.db.models import Q

from .models import RefillReminder, WarrantyReminder, MaintenanceReminder
from sale.models import Sale 
from job.models import Job 
from staff.models import Staff 
from inventory.models import Inventory 

from datetime import date
from datetime import datetime
from os import getlogin
import logging 
import xlsxwriter as xl 

logging.basicConfig(
    level=logging.ERROR, 
    encoding='utf-8'
)
logger = logging.getLogger()
debug = lambda text: logger.debug(text) 
info = lambda text: logger.info(text) 
warning = lambda text: logger.warning(text) 

# Create your views here.
ALL_STAFF = Staff.objects.all()
TODAY = date.today()
current_year = TODAY.year
ALL_YEARS = list(range(current_year-10, current_year+30))
MONTHS = [
        'January', 'February', 'March', 
        'April', 'May', 'June', 'July', 
        'August', 'September', 'October', 
        'November', 'December'
    ]
ALL_INVENTORY = Inventory.objects.filter(deactivate=False) 
ALL_SALES = Sale.objects.all() 
ALL_JOBS = Job.objects.all() 

# days_in_a_month = 30 

def homeView(request):
    context = {} 
    return render(request, 'core/home.html', context)

def helpView(request):
    context = {}
    return render(request, 'core/help.html', context)

def listify(obj_string, obj_type): 
    obj_list = []
    for obj_string_item in obj_string.split(','):
        if obj_string_item: 
            obj_list.append(obj_type(obj_string_item))
    return obj_list
    
def getCellName(row, col):
    r = row + 1
    c = chr(col + 65)
    cell_name = c + str(r) 
    return cell_name 

def exportReport(search_results): 
    '''
    Export the report, filtered or not, to an excel file saved in the Documents 
    folder on the computer 
    ''' 
    # # print('Exporting')
    monthly_sale_transactions = {}
    monthly_job_transactions = {}
    sales = search_results['monthly_sale_transactions']
    jobs = search_results['monthly_job_transactions'] 
    months = search_results['months'] if search_results['months'] else MONTHS
    
    # Match months to the sales and jobs completed in them 
    for month in MONTHS: 
        month_ind = MONTHS.index(month) + 1
        monthly_sale_transactions[month] = [
            *[sale for sale in sales if sale.date.month == month_ind], 
        ]
        monthly_job_transactions[month] = [
            *[job for job in jobs if job.date.month == month_ind]
        ]

    # # print(monthly_sale_transactions)
    # # print(monthly_job_transactions)

    username = getlogin()
    unique_ms = datetime.now().microsecond
    unique_id = f"{TODAY.day}{TODAY.month}{TODAY.year}_{unique_ms}"
    workbook = xl.Workbook(f"C:/Users/{username}/Documents/Report_{unique_id}.xlsx") 
    worksheet = workbook.add_worksheet()

    title_format = workbook.add_format({
            'bold': True, 
            # 'underline': True, 
            'align': 'center', 
            'font_size': 20})
    p1, p2 = getCellName(0,0), getCellName(0,14)
    worksheet.merge_range(f'{p1}:{p2}', 'Sales and Jobs Report', title_format)

    # Write sales report 
    sales_headings = [
        'Date', 'Good Sold', 'Unit Price', 'Quantity', 'Serial Numbers', 
        'Customer', 'Phone', 'Details'
    ]
    transaction_format = workbook.add_format({
            'bold': True, 
            'align': 'center', 
            'font_color': 'red', 
            'font_size': 16})
    month_format = workbook.add_format({
            'bold': True, 
            'font_color': 'blue'})
    bold_format = workbook.add_format({'bold': True})
    p1_sales, p2_sales = getCellName(1,0), getCellName(1,6)
    worksheet.merge_range(f'{p1_sales}:{p2_sales}', 'Sales', transaction_format)
    row = 2; col = 0
    for month in months: 
        if monthly_sale_transactions[month]:
            col = 0
            worksheet.write(row, col, month, month_format) 
            row += 1 
            # Headers
            for header in sales_headings:
                worksheet.write(row, col, header, bold_format)
                col += 1
            row += 1
            # For each sale 
            for sale in monthly_sale_transactions[month]:
                first_sale_row = row 
                col = 0
                goods = listify(sale.goods_sold, str) 
                prices = listify(sale.prices, float) 
                quantities = listify(sale.quantities, int) 
                # Date
                worksheet.write(row, col, str(sale.date))
                # 
                col += 1
                # Good sold, unit price, quantity 
                for i in range(len(goods)):
                    worksheet.write(row, col, goods[i]) # Good sold
                    worksheet.write(row, col+1, prices[i])  #  Unit price
                    worksheet.write(row, col+2, quantities[i])  # Quantiy
                    row += 1
                # Total 
                worksheet.write(row, col, 'Total', bold_format)
                worksheet.write(row, col+1, sale.total)
                
                last_sale_row = row
                row = first_sale_row
                # Serial numbers 
                col += 3
                batt_serials = eval(sale.battery_serials) 
                invt_serials = eval(sale.inverter_serials) 
                for good in goods: 
                    if good in batt_serials: 
                        worksheet.write(row, col, batt_serials[good])

                    if good in invt_serials: 
                        worksheet.write(row, col, invt_serials[good])
                    row += 1

                # Customer
                col += 1
                row = first_sale_row
                worksheet.write(row, col, sale.customer_name) # Customer
                col += 1
                worksheet.write(row, col, sale.customer_phone)    # Phone 
                col += 1
                worksheet.write(row, col, sale.details) # Details
                row = last_sale_row

                # Empty row
                row += 1
                worksheet.write(row, col, '')
        
            # Empty row
            row += 1
            worksheet.write(row, col, '')

    # Empty row
    row += 1
    worksheet.write(row, col, '')

    # Write job report 
    jobs_headings = [
        'Date', 'Inventory Used', 'Unit Price', 'Quantity', 
        'Serial Numbers', 'Extra Item', 'Extra Cost', 
        'Staff Assigned', 'Location', 'Status', 'Description',
        'Customer', 'Phone', 'Remark', 'Customer Fee'
    ]
    col = 0
    # # print('Job start', row, col) 
    p1_jobs, p2_jobs = getCellName(row,0), getCellName(row,14)
    worksheet.merge_range(f'{p1_jobs}:{p2_jobs}', 'Jobs', transaction_format)
    row += 1
    for month in months: 
        if monthly_job_transactions[month]:
            col = 0
            worksheet.write(row, col, month, month_format) 
            row += 1 
            # Headers
            for header in jobs_headings:
                worksheet.write(row, col, header, bold_format)
                col += 1
            row += 1
            # For each job 
            for job in monthly_job_transactions[month]:
                first_good_row = row 
                col = 0
                goods = listify(job.inventory_used, str) 
                prices = listify(job.prices, float) 
                quantities = listify(job.quantities, int) 
                other_items = listify(job.other_items, str)
                other_items.append('Transportation') 
                other_costs = listify(job.other_items_expenses, float) 
                other_costs.append(job.transportation_cost)
                staff_assigned = listify(job.staff_assigned, str)
                # Date
                worksheet.write(row, col, str(job.date))
                # 
                col += 1
                # # print('before goods', row, col)
                for i in range(len(goods)):
                    worksheet.write(row, col, goods[i]) # Good sold
                    worksheet.write(row, col+1, prices[i])  #  Unit price
                    worksheet.write(row, col+2, quantities[i])  # Quantiy
                    row += 1

                job_last_row = (first_good_row + max(len(goods), len(other_items), len(staff_assigned)) + 1)

                # # print('after goods', row, col) 
                last_good_row = row
                row = first_good_row

                # Serial numbers 
                col += 3
                batt_serials = eval(job.battery_serials) 
                invt_serials = eval(job.inverter_serials) 
                for good in goods: 
                    if good in batt_serials: 
                        worksheet.write(row, col, batt_serials[good])

                    if good in invt_serials: 
                        worksheet.write(row, col, invt_serials[good])
                    row += 1

                # Customer
                col += 1
                row = first_good_row
                # Extra items and costs
                for item, cost in zip(other_items, other_costs):
                    worksheet.write(row, col, item)
                    worksheet.write(row, col+1, cost) 
                    row += 1
                # Other Items 
                worksheet.write(job_last_row-1, col-3, 'Total', bold_format)
                worksheet.write(job_last_row-1, col-2, job.total_expenses)
                # # print(job_last_row, col-3, 'Total')
                # Staff Assigned 
                col += 2 
                row = first_good_row
                for i, staff in enumerate(staff_assigned): 
                    worksheet.write(row+i, col, staff)


core/templates/core/base.html
{% load static %} 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Base{% endblock %}</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <style>
        a, th, .crimson {
            text-decoration: none;
            color: crimson;
        }
        a:hover {
            color: darkgreen;
        }
        .footer>.row>.col>a {
            color: gray;
        }
        .footer>.row>.col>a:hover {
            color: rgb(11, 129, 129);
        }
        .detail {
            font-size: large;
        }
        .label {
            font-weight: bold;
        }
        .font-table {
            font-size: larger;
        }
        .hidden {
            visibility: hidden;
        }
    </style>
    {% block style %}{% endblock %}
</head>
<body>
    {% block content %} 
        Base 
    {% endblock %} 

    
    <div class="footer">
        <div class="row row-cols-4 my-5 p-3 text-muted bg-dark text-center">
            <div class="col detail">
                <a href="{% url 'core:home' %}">Home</a>
            </div>
            <div class="col detail">
                <a href="{% url 'staff:staff-list' %}">Staff</a>
            </div>
            <div class="col detail">
                <a href="{% url 'inventory:inventory-list' %}">Inventory</a>
            </div>
            <div class="col detail">
                <a href="{% url 'sale:sale-list' %}">Sales</a>
            </div>
            <div class="col detail">
                <a href="{% url 'job:job-list' %}">Jobs</a>
            </div>
            <div class="col detail">
                <a href="{% url 'core:report' %}">Report</a>
            </div>
            <div class="col detail`">
                <a href="{% url 'core:reminder' %}">Reminders</a>
            </div>
            <div class="col detail">
                <a href="{% url 'core:help' %}">Help</a>
            </div>
        </div>
    </div>
</body>
</html>

core/templates/core/home.html
{% extends 'core/base.html' %} 
{% load static %}
{% block title %}Home{% endblock %} 

{% block style %}
<style>
    body {
        background-image: url({% static 'images/legend_back.png' %});
        background-repeat: no-repeat; 
    }
    a { 
        color: purple;
    }
</style>
{% endblock %}

{% block content %} 
<div class="container">
    <div class="row display-4 text- title">
        <div class="col"><img src="{% static 'images/legendary-logo-small.jpg' %}" alt="legendary logo">
        </div>
        <div class="col-7 text-end">D-LEGENDARY ENERGY CONCEPT</div>
    </div>
    <hr>
    <div class="row row-cols-1 navigation h3 crimson text-center">
        <div class="col display-5">
            <a href="{% url 'staff:staff-list' %}">Staff</a>
        </div>
        <div class="col display-5">
            <a href="{% url 'inventory:inventory-list' %}">Inventory</a>
        </div>
        <div class="col display-5">
            <a href="{% url 'sale:sale-list' %}">Sales</a>
        </div>
        <div class="col display-5">
            <a href="{% url 'job:job-list' %}">Jobs</a>
        </div>
        <div class="col display-5">
            <a href="{% url 'core:report' %}">Report</a>
        </div>
        <div class="col display-5">
            <a href="{% url 'core:reminder' %}">Reminders</a>
        </div>
        
    </div>

    <!-- <p>
        OBJECTIVES 
    </p>
    <p>
        HIGHLIGHTS OF JOBS DONE 
        <img src="{% static 'images/serena.jpg' %}" alt="" srcset="">
    </p>
    <p>
        IMAGES OF PRODUCTS ON SALE 
    </p>
    <p>
        PHOTOS OF STAFF 
    </p> -->
</div>

{% endblock %}  

core/templates/core/reminders.html
{% extends 'core/base.html' %} 
{% load static %}
{% block title %}Reminders{% endblock %} 


{% block content %} 

<div class="container">
    <form action="{% url 'core:reminder-handle' %}" method="post">{% csrf_token %} 
    <div class="row g-3">
        <div class="col display-1">Reminders</div>
        <div class="col-3 mt-5">
            <a class="h4" href="{% url 'core:home' %}">Home</a>
        </div>
        <div class="col-2 mt-5">
            <button type="submit" class="btn btn-success btn-lg">Save</button>
        </div>
    </div>
    <hr>

    <div class="h2">
        Battery Refill Reminders
    </div>
    <table class="table">
        <tr class="">
            <th>Customer name</th>
            <th>Location</th>
            <th>Transaction</th>
            <th>Last Refill</th>
            <th>Handled</th>
            <th class="text-muted">Forget</th>
        </tr>
        {% for rem in refill_reminders %} 
        {% if rem.sale %}
            <tr>
                <td>{{ rem.sale.customer_name }}</td>
                <td></td>
                <td><a href="{% url 'sale:sale-detail' rem.sale.id %}">{{ rem.sale.date }}</a></td>
                <td>{{ rem.last_refill_date }}</td>
                <td><input type="checkbox" name="refill_handle_{{ rem.id }}" class="form-check-input"></td>
                <td><input type="checkbox" name="refill_forget_{{ rem.id }}" class="form-check-input"></td>
            </tr>
        {% else %}
            <tr>
                <td>{{ rem.job.customer_name }}</td>
                <td>{{ rem.job.location|title }}</td>
                <td><a href="{% url 'job:job-detail' rem.job.id %}">{{ rem.job.date }}</a></td>
                <td>{{ rem.last_refill_date }}</td>
                <td><input type="checkbox" name="refill_handle_{{ rem.id }}" class="form-check-input"></td>
                <td><input type="checkbox" name="refill_forget_{{ rem.id }}" class="form-check-input"></td>
            </tr>
        {% endif %}
        {% endfor %}
    </table>
    
    <div class="h2">Maintenance Reminders</div>
    <table class="table">
        <tr>
            <th>Customer name</th>
            <th>Location</th>
            <th>Job</th>
            <th>Last Maintenance</th>
            <th>Handled</th>
            <th class="text-muted">Forget</th>
        </tr>
        {% for rem in maintenance_reminders %} 
            <tr>
                <td>{{ rem.job.customer_name }}</td>
                <td>{{ rem.job.location|title }}</td>
                <td><a href="{% url 'job:job-detail' rem.job.id %}">{{ rem.job.date }}</a></td>
                <td>{{ rem.last_maintenance_date }}</td>
                <td><input type="checkbox" name="maintain_handle_{{ rem.id }}" class="form-check-input"></td>
                <td><input type="checkbox" name="maintain_forget_{{ rem.id }}" class="form-check-input"></td>
            </tr>
        {% endfor %}
    </table>
    
    <div class="h2">Expired Warranty Reminders</div>
    <table class="table">
        <tr>
            <th>Customer name</th>
            <th>Product</th>
            <th>Serial number</th>
            <th>Transaction</th>
            <th class="text-muted">Forget</th>
        </tr>
        {% for rem in sale_warranty_reminders %} 
        <tr>
            <td>{{ rem.sale.customer_name }}</td>
            <td>{{ rem.product }}</td>
            <td>{{ rem.serial_no }}</td>
            <td><a href="{% url 'sale:sale-detail' rem.sale.id %}">{{ rem.sale.date }}</a></td>
            <td><input type="checkbox" name="warranty_handle_{{ rem.id }}" class="form-check-input"></td>
            <!-- <td><input type="checkbox" name="warranty_forget_{{ rem.id }}" class="form-check-input"></td> -->
        </tr>
        {% endfor %}

        {% for rem in job_warranty_reminders %} 
        <tr>
            <td>{{ rem.job.customer_name }}</td>
            <td>{{ rem.product }}</td>
            <td>{{ rem.serial_no }}</td>
            <td><a href="{% url 'job:job-detail' rem.job.id %}">{{ rem.job.date }}</a></td>
            <td><input type="checkbox" name="warranty_handle_{{ rem.id }}" class="form-check-input"></td>
            <!-- <td><input type="checkbox" name="warranty_forget_{{ rem.id }}" class="form-check-input"></td> -->
        </tr>
        {% endfor %}
    </table>
    </form>
</div>
{% endblock %} 

core/templates/core/report.html
{% extends 'core/base.html' %} 
{% load custom_tags %} 

{% block title %}Generate Report{% endblock %} 

{% block content %} 
<div class="container">
    <div class="row gt-5">
        <div class="col-8 display-2 crimson">Sales and Jobs Report</div>
        <div class="col mt-5"><a class="h4" href="{% url 'core:home' %}">Home</a></div>
    </div>
    <hr>
    {% for month in months %} 
    <div class="row detail border border-3 rounded-2 my-2 p-3">
        <div class="row h3">{{ month }}</div>
        <div class="row row-cols-1">
            <ul>
                {% for list_item in monthly_sale_transactions|get_value:month %} 
                    <li>
                        <div class="row">
                            <div class="col"><a href="{% url 'sale:sale-detail' list_item.id %}">Sale on {{ list_item.date }}</a></div>
                            <div class="col"> N{{ list_item.total }}</div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            {% if monthly_sale_transactions|get_value:month and monthly_job_transactions|get_value:month %}<hr>{% endif %}

            <ul>
                {% for list_item in monthly_job_transactions|get_value:month %} 
                    <li>
                        <div class="row">
                            <div class="col"><a href="{% url 'job:job-detail' list_item.id %}">Job on {{ list_item.date }}</a></div>
                            <div class="col">N{{ list_item.total_expenses }}</div>
                        </div>
                    </li>
            {% endfor %}
            </ul>
        </div>
    </div>
    {% endfor %}

    <!-- filter -->
    <div class="row filter border border-dark my-2 p-3">
        <div class="row">
            <div class="col display-4">Filter</div>
        </div>

        <div class="row">
            <form action="{% url 'core:filter' %}" method="post">{% csrf_token %}
                <div class="row">Year
                    <select name="year" class="form-control form-select">
                        <option value="----">All</option>
                        {% for y in all_years %} 
                        <option value="{{ y }}">{{ y }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="row">
                    Month
                    <input type="month" name="month" id="" class="form-control">
                </div>
                <div class="row">
                    Staff assigned
                    <select name="staff_assigned" class="form-control" id="">
                        <option value="----">All</option>
                        {% for staff in all_staff %} 
                        <option value="{{ staff.name }}">{{ staff.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="row">
                    Goods sold
                    <select name="goods_sold" class="form-control" id="">
                        <option value="----">All</option>
                        {% for inv in all_inventory %} 
                        <option value="{{ inv.name }}">{{ inv.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="row">
                    Location 
                    <input type="text" name="location" class="form-control">
                </div>
                <div class="row my-3">
                    <label for="transaction_type">Transaction type</label>
                    <div class="col">
                        <input type="radio" value="all" name="transaction_type" checked id="All" class="form-check-input"> All
                    </div>
                    <div class="col">
                        <input type="radio" value="sale" name="transaction_type" id="Sale" class="form-check-input"> Sale
                    </div>
                    <div class="col">
                        <input type="radio" value="job" name="transaction_type" id="Job" class="form-check-input"> Job
                    </div>
                </div>
                <input type="checkbox" value="export" name="export" id="" class="mb-3 form-check-input"> Export to Excel sheet
                <div class="row">
                    <div class="col-5 mx-3 btn btn-secondary mt-2 text-center"><a class="mx-auto btn text-white my-auto" href="../">Home</a></div>
                    <div class="col-5 mx-3 mt-auto btn btn-success"><button type="submit" class="mx-auto btn text-white my-auto">Filter</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}