api/urls.py
from django.urls import path 
from .views import (
    StaffListCreateAPIView, 
    StaffDetailAPIView, 
    StaffDestroyAPIView, 
    InventoryListCreateAPIView, 
    InventoryDetailAPIView, 
    InventoryDestroyAPIView, 
    SaleListCreateAPIView, 
    SaleDetailAPIView, 
    SaleDestroyAPIView, 
    JobListCreateAPIView, 
    JobDetailAPIView, 
    JobDestroyAPIView, 
    InventoryTypeListCreateAPIView, 
    InventoryTypeDetailAPIView, 
    InventoryTypeDestroyAPIView
)

app_name = 'api'
urlpatterns = [
    path('staff_list/', StaffListCreateAPIView.as_view()), 
    path('staff_detail/<int:pk>/', StaffDetailAPIView.as_view()), 
    path('staff_delete/<int:pk>/', StaffDestroyAPIView.as_view()), 

    path('inventory_list/', InventoryListCreateAPIView.as_view()), 
    path('inventory_detail/<int:pk>/', InventoryDetailAPIView.as_view()), 
    path('inventory_delete/<int:pk>/', InventoryDestroyAPIView.as_view()), 

    path('sale_list/', SaleListCreateAPIView.as_view()), 
    path('sale_detail/<int:pk>/', SaleDetailAPIView.as_view()), 
    path('sale_delete/<int:pk>/', SaleDestroyAPIView.as_view()), 
    
    path('job_list/', JobListCreateAPIView.as_view()), 
    path('job_detail/<int:pk>/', JobDetailAPIView.as_view()), 
    path('job_delete/<int:pk>/', JobDestroyAPIView.as_view()), 

    path('inv_type_list/', InventoryTypeListCreateAPIView.as_view()), 
    path('inv_type_detail/<int:pk>/', InventoryTypeDetailAPIView.as_view()), 
    path('inv_type_delete/<int:pk>/', InventoryTypeDestroyAPIView.as_view()), 

]

core/urls.py
from django.urls import path 
from django.conf import settings 
from django.conf.urls.static import static 
from .views import (
    homeView,
    reportView, 
    filterView, 
    reminderCreateView, 
    reminderHandleView, 
    helpView, 
)

app_name = 'core'
urlpatterns = [
    path('', homeView, name='home'), 
    path('report/', reportView, name='report'), 
    path('filter/', filterView, name='filter'), 
    path('reminders/', reminderCreateView, name='reminder'), 
    path('reminder-handle/', reminderHandleView, name='reminder-handle'), 
    path('help/', helpView, name='help'), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/urls.py
from django.urls import path 
from django.conf import settings 
from django.conf.urls.static import static 

from .views import (
    jobCreateView, 
    JobDeleteView, 
    JobDetailView, 
    JobListView, 
    JobUpdateView
)

app_name = 'job'
urlpatterns = [
    path('list/', JobListView.as_view(), name='job-list'), 
    path('<int:id>/', JobDetailView.as_view(), name='job-detail'), 
    path('<int:id>/delete/', JobDeleteView.as_view(), name='job-delete'), 
    path('create/', jobCreateView, name='job-create'), 
    path('<int:id>/update/', JobUpdateView.as_view(), name='job-update'),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

legend/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')), 
    path('core/', include('core.urls')), 
    path('staff/', include('staff.urls')), 
    path('inventory/', include('inventory.urls')), 
    path('job/', include('job.urls')), 
    path('sale/', include('sale.urls')), 
]

sale/urls.py
from django.urls import path 
from .views import (
    # SaleCreateView, 
    SaleDetailView, 
    SaleConfirmDeleteView, 
    SaleListView, 
    saleDelete, 
    saleCreateView, 
    saleDetailView, 
    saleUpdateView
)

app_name = 'sale'
urlpatterns = [
    path('list/', SaleListView.as_view(), name='sale-list'), 
    # path('<int:id>/', SaleDetailView.as_view(), name='sale-detail'),
    path('<int:id>/', saleDetailView, name='sale-detail'), 
    path('<int:id>delete/', saleDelete, name='sale-delete'), 
    path('<int:id>/confirm_delete/', SaleConfirmDeleteView.as_view(), name='sale-confirm-delete'), 
    # path('create/', SaleCreateView.as_view(), name='sale-create'), 
    path('create/', saleCreateView, name='sale-create'), 
    path('<int:id>/update/', saleUpdateView, name='sale-update')
]

staff/urls.py
from django.urls import path 
from django.conf import settings 
from django.conf.urls.static import static 
from .views import (
    staffCreateView, 
    StaffDeleteView, 
    StaffDetailView, 
    StaffListView, 
    StaffUpdateView,
    staffListView, 
)

app_name = 'staff'
urlpatterns = [
    path('list/', StaffListView.as_view(), name='staff-list'), 
    path('<int:pk>/', StaffDetailView.as_view(), name='staff-detail'), 
    # path('create/', StaffCreateView.as_view(), name='staff-create'), 
    path('create/', staffCreateView, name='staff-create'), 
    path('<int:pk>/update/', StaffUpdateView.as_view(), name='staff-update'), 
    path('<int:pk>/delete/', StaffDeleteView.as_view(), name='staff-delete')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sale/models.py
from django.db import models
from django.urls import reverse
# from inventory.models import Inventory 

from datetime import date 

# Create your models here.
class Sale(models.Model):
    goods_sold = models.CharField(max_length=200, default='', null=False) 
    prices = models.CharField(max_length=200, default='', null=False) 
    quantities = models.CharField(max_length=100, blank=False, null=True) 
    total = models.DecimalField(max_digits=20, decimal_places=2, null=True) 
    customer_name = models.CharField(max_length=200, blank=True, null=True) 
    customer_phone = models.CharField(max_length=15, blank=True, null=True) 
    date = models.DateField(default=date.today) 
    details = models.TextField(blank=True, null=True) 
    
    battery_serials = models.CharField(max_length=400, default='{}') # string of dict mapping battery name to serial numbers
    inverter_serials = models.CharField(max_length=400, default='{}') # string of dict mapping inverter name to serial numbers
    battery_serials_done = models.CharField(max_length=400, default='', blank=True, null=True)
    inverter_serials_done = models.CharField(max_length=300, default='', blank=True, null=True) 

    has_refill_reminder = models.BooleanField(default=False) 

    def get_absolute_url(self):
        return reverse('sale:sale-detail', kwargs={'pk': self.id})

    def __str__(self):
        return str(self.date)


sale/forms.py
from django import forms 
from .models import Sale
from inventory.models import Inventory 

class SaleCreationForm(forms.ModelForm):

    goods_choices = [
        (inv, inv.name) for inv in Inventory.objects.all()
    ]
    goods_sold = forms.MultipleChoiceField(
        choices=goods_choices, 
        widget=forms.CheckboxSelectMultiple(), 
        required=True
    )
    profit = forms.DecimalField(
        required=True, 
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control' 
            }
        )
    )
    customer_name = forms.CharField(
        required=False, 
        widget=forms.TextInput(
            attrs={
                'class': 'form-control' 
            }
        )
    )
    customer_phone = forms.CharField(
        required=False, 
        widget=forms.TextInput(
            attrs={
                'class': 'form-control' 
            }
        )
    )
    date = forms.DateField(
        required=False, 
        widget=forms.DateInput(
            attrs={
                'class': 'form-control'
            }
        )
    )
    remark = forms.CharField(
        required=False, 
        widget=forms.Textarea(
            attrs={
                'class': 'form-control'
            }
        )
    )

    class Meta:
        model = Sale 
        fields = '__all__' 


sale/views.py
from django.shortcuts import render, redirect
from django.views.generic import (
    CreateView, 
    DetailView, 
    ListView, 
    UpdateView, 
    DeleteView
)
from django.views import View
from .models import Sale 
from inventory.models import Inventory 
# from .forms import SaleCreationForm 

from datetime import date as theDate 

# Create your views here
def listify(obj_string, obj_type): 
    obj_list = []
    for obj_string_item in obj_string.split(','):
        if obj_string_item: 
            obj_list.append(obj_type(obj_string_item))
    return obj_list
  

class SaleListView(ListView):
    template_name = 'sale/sale_list.html'
    queryset = Sale.objects.all().order_by('-date')#.reverse()


class SaleDetailView(DetailView):
    template_name = 'sale/sale_detail.html'
    queryset = Sale.objects.all() 
    
    def get_object(self):
        pk_ = self.kwargs.get('id') 
        obj = Sale.objects.get(pk=pk_) 
        return obj 


def saleDetailView(request, id):
    ''' 
    Most of the attibutes of the Sale model are stored as strings, so 
    they will be treated as strings -- split them up, convert to 
    appropriate types and then pass to the template. 
    '''
    # # print('IN DETAIL')
    template_name = 'sale/sale_detail.html' 
    object = Sale.objects.get(id=id) 

    all_sale_inv = list(object.goods_sold.split(','))
    sale_goods_list = listify(object.goods_sold, str)
    battery_inv = [good for good in sale_goods_list if 'battery' in good.lower()]
    inverter_inv = [good for good in sale_goods_list if 'inverter' in good.lower()]

    # # print(all_sale_inv) 
    for i, inv in enumerate(all_sale_inv[:]):
        all_sale_inv[i] = inv.strip()
    all_sale_prices = list(object.prices.split(',')) 
    all_sale_quantities = list(object.quantities.split(',')) 
    for i in range(len(all_sale_prices)):
        # # # print(all_sale_prices) 
        all_sale_prices[i] = float(all_sale_prices[i]) 
        all_sale_quantities[i] = int(all_sale_quantities[i]) # 

    indexes = list(range(len(all_sale_inv))) 
    # print(indexes) 
    # print(all_sale_inv)
    # print('Prices', all_sale_prices) 
    # print(all_sale_quantities) 
    zipped_details = zip(all_sale_inv, all_sale_prices, all_sale_quantities)
    
    context = {
        'object': object, 
        'indexes': indexes, 
        'zipped': zipped_details, 
        'battery_inv': battery_inv, 
        'inverter_inv': inverter_inv, 
        'batt_serials': eval(object.battery_serials), 
        'invt_serials': eval(object.inverter_serials), 
    }

    return render(request, template_name, context)     


def saleCreateView(request):
    '''
    Create a sale, store the goods sold, the customer's details and the date
    The data from the form is collected, converted to and stored as strings
    The quantity of inventory sold should be deducted from the amount in stock
    ''' 
    # print('IN CREATE')
    template_name = 'sale/sale_create.html' 
    all_inv = Inventory.objects.filter(deactivate=False)
    all_inv_names = [inv for inv in all_inv]
    battery_inv = all_inv.filter(type__name='Battery')
    inverter_inv = all_inv.filter(type__name='Inverter')

    if request.method == 'POST': 
        # form = {}
        form = request.POST  
        # # print(form) 
        
        goods = '' 
        prices = '' 
        quantities = ''
        total = 0.00 
        details = '' 

        #########################33
        ''' Extract the goods, prices, and quantities from the form data '''
        for inv in all_inv_names:
            try: 
                good_ = form.get(inv.name)
                price_ = form.get(inv.name + '_price')
                quantity_ = form.get(inv.name + '_quantity') 
                # print('Creation:', inv.name, good_, price_, quantity_, type(quantity_)) 

                if good_ and float(price_) and int(quantity_):
                    # print('Actual Creation:', inv.name, good_, price_, quantity_) 
                    goods += f'{inv.name},'  
                    prices += f'{price_},'
                    quantities += f'{quantity_},'
                    total += (float(price_) * int(quantity_))                
                    
            except (KeyError, TypeError, ValueError): 
                continue 

        goods = goods.removesuffix(',') 
        prices = prices.removesuffix(',') 
        quantities_string = quantities.removesuffix(',') 
        quantities_list = listify(quantities_string, int) 
        
        ##################################################
        '''Update Inventory'''
        # all_inv = Inventory.objects.all() 
        # # print(all_inv)
        goods_list = listify(goods, str)
        for inv in all_inv:
            if inv.name in goods_list:
                ind = goods_list.index(inv.name) 
                quan = quantities_list[ind]
                inv.quantity -= int(quan)
                inv.save()
        ##############################################3

        # Get rest of form data and create sale instance
        # Get list of serial nos, compare with number of inventories

        bat_serials = {} 
        for bat in battery_inv: 
            if bat.name in goods: 
                val = form.get(f'{bat.name}_serials')
                valid = form.get(f'{bat.name}')
                if val and valid: 
                    val = val.strip().strip(',') 
                    bat_serials[bat.name] = val 
                print('BAT_SERIALS', bat_serials) 
        battery_serials = repr(bat_serials) 

        invt_serials = {}
        for invt in inverter_inv: 
            print('Goods', goods, invt.name)
            if invt.name in goods: 
                val = form.get(f'{invt.name}_serials')
                valid = form.get(f'{invt.name}')
                if val and valid: 
                    val = val.strip().strip(',') 
                    invt_serials[invt.name] = val
        inverter_serials = repr(invt_serials) 

        #####################################
        # Re-render create page with error message if no goods were actually sold
        quantity_serial_tally = True 
        for inv in all_inv:
            try:
                quantity_ = form.get(inv.name + '_quantity') 
                if len(listify(bat_serials[inv.name], str)) > int(quantity_): 
                    quantity_serial_tally = False
                elif len(listify(invt_serials[inv.name], str)) > int(quantity_): 
                    quantity_serial_tally = False 
            except (KeyError, AttributeError, ValueError): 
                pass 
            
        refresh = False 
        if not quantity_serial_tally: 
            no_good_error = '**The serial numbers cannot be more than the quantities of goods sold**'
            refresh = True 
        if goods == '':
            no_good_error = 'Please select one or more goods and enter correct prices and quantities'
            refresh = True 
        if refresh: 
            context = {
                'all_inv_names': all_inv_names, 
                'no_good_error': no_good_error,
                'battery_inv': battery_inv, 
                'inverter_inv': inverter_inv, 
            }
            return render(request, template_name, context)
    
        #################################

        customer_name = form.get('customer_name') 
        customer_phone = form.get('customer_phone') 
        date = form.get('date') 
        details = form.get('details')

        if not date:
            date = theDate.today()

        instance = Sale.objects.create(
            goods_sold = goods, 
            prices = prices,
            total=total, 
            quantities = quantities_string, 
            battery_serials=battery_serials,
            inverter_serials=inverter_serials, 
            customer_name=customer_name, 
            customer_phone=customer_phone, 
            date=date, 
            details=details
        )
        instance.save() 
        # print('Done with create')
        return redirect('../list/')

    elif request.method == 'GET': 
        context = {
            'all_inv_names' : all_inv_names, 
            'battery_inv': battery_inv, 
            'inverter_inv': inverter_inv, 
            }
        return render(request, template_name, context)


def saleUpdateView(request, id):
    # print('IN UPDATE')
    object = Sale.objects.get(id=id) 
    template_name = 'sale/sale_update.html' 
    object = Sale.objects.get(id=id) 
    all_sale_inv = Inventory.objects.filter(deactivate=False)
    all_goods = object.goods_sold.split(',')
    # sale_goods_list = listify(object.goods_sold, str)
    battery_inv = [good for good in all_sale_inv if 'battery' in good.name.lower()]
    inverter_inv = [good for good in all_sale_inv if 'inverter' in good.name.lower() ]
    obj_batt_serials = object.battery_serials
    obj_invt_serials = object.inverter_serials

    if request.method == 'POST': 
        form = request.POST  
        # print('form:', form) 

        # Extract data from form 
        goods = '' 
        prices = '' 
        quantities = ''
        total = 0.00 
        quantity_serial_tally = True 

        bat_serials = {} 
        for bat in battery_inv: 
            bat_serials[bat.name] = form.get(f'{bat}_serials').strip()
            # print('check 1:', bat_serials)
        battery_serials = repr(bat_serials) 
        
        inv_serials = {}
        for invt in inverter_inv: 
            inv_serials[invt.name] = form.get(f'{invt}_serials').strip()
        inverter_serials = repr(inv_serials)

        for inv in all_sale_inv:
            try: 
                good_ = form.get(inv.name)

sale/templates/sale/base.html
{% load static %} 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Base{% endblock %}</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <style>
        a, th, .crimson {
            text-decoration: none;
            color: crimson;
        }
        a:hover {
            color: darkgreen;
        }
        .detail {
            font-size: large;
        }
        .label {
            font-weight: bold;
        }
        .font-table {
            font-size: larger;
        }
        .small {
            font-size: smaller;
        }
        .tiny {
            font-size: x-small;
        }
        .thick {
            font-weight: bold;
        }
        .footer>.row>.col>a {
            color: gray;
        }
        .footer>.row>.col>a:hover {
            color: rgb(11, 129, 129);
        }
    </style>
</head>
<body>
    {% block content %} 
        Base 
    {% endblock %} 

    <div class="footer">
        <div class="row row-cols-4 my-5 p-3 text-muted bg-dark text-center">
            <div class="col detail">
                <a href="{% url 'core:home' %}">Home</a>
            </div>
            <div class="col detail">
                <a href="{% url 'staff:staff-list' %}">Staff</a>
            </div>
            <div class="col detail">
                <a href="{% url 'inventory:inventory-list' %}">Inventory</a>
            </div>
            <div class="col detail">
                <a href="{% url 'sale:sale-list' %}">Sales</a>
            </div>
            <div class="col detail">
                <a href="{% url 'job:job-list' %}">Jobs</a>
            </div>
            <div class="col detail">
                <a href="{% url 'core:report' %}">Report</a>
            </div>
            <div class="col detail`">
                <a href="{% url 'core:reminder' %}">Reminders</a>
            </div>
            <div class="col detail">
                <a href="{% url 'core:help' %}">Help</a>
            </div>
        </div>
    </div>
</body>
</html>

sale/templates/sale/sale_confirm_delete.html
{% extends 'sale/base.html' %} 

{% block title %}Confirm Delete{% endblock %} 

{% block content %} 

<div class="container">
    <div class="row display-4">
        Confirm Delete
    </div>
    <div class="row">
        <p class="detail">Are you sure you want to delete this sale record?</p>
        <p class="text-primary display-4">{{ object.date }}</p>
        <div class="row">
            <div class="col mx-2 btn btn-secondary py-3">
                <a href="{% url 'sale:sale-detail' object.id %}"><span class="text-white">Cancel</span>
                </a>
            </div>
            <div class="col mx-2 text-white btn btn-danger">
                <form method="post" action="{% url 'sale:sale-confirm-delete' object.id %}">{% csrf_token %}
                    <button type="submit" class="btn btn-danger">Confirm</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

sale/templates/sale/sale_create.html
{% extends 'sale/base.html' %} 

{% block title %}Record A Sale{% endblock %} 

{% block content %} 

<div class="container">
    <div class="row display-2 crimson">
        Record A Sale
    </div>
    <hr>
    <form action="{% url 'sale:sale-create' %}" method="post">{% csrf_token %}
        
        {% if no_good_error %} 
        <div class="row detail text-danger">
            {{ no_good_error }}
        </div>
        {% endif %}
        
        <!-- inventory details  -->
        <div class="goods-sold row py-3 border">
            <div class="col">
                <div class="row label">
                    <div class="col-4 text-center">Good Sold</div>
                    <div class="col-4 text-center">Unit Price</div>
                    <div class="col-4 text-center">Quantity</div>
                </div>
                {% for inv in all_inv_names %} 
                    <div class="row mx-2">
                        <div class="col-5">
                            <div class="row">
                                <div class="col-2">
                                    <input type="checkbox" name="{{ inv.name }}" class="form-check-input mx-1"
                                    id="{{ inv.name }}">
                                </div> 
                                <div class="col-8">
                                    <label for="{{ inv.name }}" class="form-check-label">{{ inv.name }}</label>
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <input type="number" name="{{ inv.name }}_price" class="form-control" value="{{ inv.unit_price }}">
                        </div>
                        <div class="col-3">
                            <input type="number" name="{{ inv.name }}_quantity" class="form-control">
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <!-- serial numbers -->
        <div class="row my-2">
            <label for="">
                <div class="row"><span class="text-muted detail">Battery Serial Numbers</span></div>
                <div class=" border border-danger p-2 rounded">
                    {% for bat in battery_inv %} 
                    <div class="row">
                        <div class="col-4">{{ bat.name }}</div>
                        <div class="col-7">
                            <textarea name="{{ bat.name }}_serials" 
                                cols="30" rows="2"
                                placeholder="serial_num1, serial_num2, ..."
                                class="form-control small"></textarea>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </label>
        </div>

        <div class="row my-2">
            <label for="">
                <div class="row"><span class="text-muted detail">Inverter Serial Numbers</span></div>
                <div class=" border border-danger p-2 rounded">
                    {% for inverter in inverter_inv %} 
                    <div class="row">
                        <div class="col-4">{{ inverter.name }}</div>
                        <div class="col-7">
                            <textarea name="{{ inverter.name }}_serials" 
                                cols="30" rows="2"
                                placeholder="serial_num1, serial_num2, ..."
                                class="form-control small"></textarea>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </label>
        </div>

        <div class="row details my-2">
            <label for="details">
                <textarea 
                name="details" 
                class="form-control" 
                cols="30" 
                rows="4"
                placeholder="Details"></textarea>
            </label>
        </div>

        <!-- customer details  -->
        <div class="row customer_name mx-auto my-2">
            <input type="text" 
            name="customer_name" 
            placeholder="Customer Name"
            class="form-control" >
        </div>

        <div class="row customer_phone mx-auto my-2">
            <input type="text" 
            name="customer_phone" 
            placeholder="Customer Phone Number"
            class="form-control" >
        </div>

        <div class="row date mx-auto my-2">
            <input type="date" name="date" class="form-control" >
        </div>


        <div class="row">
            <div class="col-5 mx-3 btn btn-secondary my-2 text-center pt-3"><a class="text-white" href="../list/">Cancel</a></div>
            <div class="col-5 mx-3 btn btn-success my-2"><button type="submit" class="mx-auto btn text-white my-2">Save</button>
            </div>
        </div>

    </form>
</div>

{% endblock %}

sale/templates/sale/sale_detail.html
{% extends 'sale/base.html' %} 
{% load custom_tags %} 

{% block title %}Sale Detail{% endblock %} 

{% block content %} 

<div class="container">
    <!-- Sale data  -->
    <div class="row rounded m-2 g-3">
        <div class="row display-2">
         Sold on {{ object.date }}
        </div>
        <hr>
        <div class="row font-table">
            <table class="table table-hover">
                <tr>
                    <th>Good sold</th>
                    <th>Price</th>
                    <th>Quantity</th>
                </tr>
                {% for inv, price, quantity in zipped %}
                <tr>
                    <td>
                        {{ inv }}
                    </td>
                    <td>
                        {{ price }}
                    </td>
                    <td>
                        {{ quantity }}
                    </td>
                </tr>
                {% endfor %}
                <tr class="table-success">
                    <th scope="row">Total:</th>
                    <td></td>
                    <td>{{ object.total }}</td>
                </tr>
            </table>
        </div>
        <hr>

        <!-- Serial Numbers -->
        <div class="row crimson label detail">
            Battery Serial Numbers:
        </div>
        <div class="row detail">
            {% for batt in battery_inv %}
                <p><span class="thick">{{ batt }}:</span> {{ batt_serials|get_value:batt }}</p>
            {% endfor %}
        </div>
        <hr>

        <div class="row crimson label detail">
            Inverter Serial Numbers:
        </div>
        <div class="row detail">
            {% for invt in inverter_inv %}
                <p><span class="thick">{{ invt }}:</span> {{ invt_serials|get_value:invt }}</p>
            {% endfor %}
        </div>
        <!-- <hr> -->

        <div class="row mt-3">
            <hr>
            <div class="col-auto label crimson">Customer:</div>
            <div class="col detail">{{ object.customer_name }}</div>
            <div class="col-auto label crimson">Phone:</div>
            <div class="col detail">{{ object.customer_phone }}</div>
        </div>
        <hr>
        <div class="row">
            <div class="col-auto label crimson">Details:</div>
            <div class="col detail">{{ object.details }}</div>
        </div>
    </div>

    <!-- footer buttons  -->
    <hr class="mb-5">

    <div class="row">
        <div class="col-3 mx-1 btn btn-primary my-2 text-center py-3">
            <a class="text-white" href="{% url 'sale:sale-list' %}">Back</a>
        </div>
        <div class="col-3 mx-auto btn btn-primary my-2 text-center py-3">
            <a class="text-white" href="{% url 'sale:sale-update' object.id %}">Update</a>
        </div>
        <div class="col-3 mx-1 btn btn-danger my-2 text-center py-3">
            <a class="text-white" href="{% url 'sale:sale-confirm-delete' object.id %}">Delete</a>
        </div>
    </div>
</div>

{% endblock %}

sale/templates/sale/sale_list.html
{% extends './base.html' %} 

{% block title %}Sale List{% endblock %} 

{% block content %} 
<div class="container">

    <div class="row g-3">
        <div class="col display-1">All Sales</div>
        <div class="col mt-5"><a class="h4" href="{% url 'sale:sale-create' %}">Record New Sale</a>
        </div>
        <div class="col mt-5"><a class="h4" href="{% url 'core:home' %}">Home</a></div>
    </div>

    <hr>

    <div class="sale my-3">
        {% for sale in object_list %} 
        <table class="table table-hover">
            <tr class="border border-3 rounded-2 my-2 py-3">
                <td class="display-5">
                    <a href="{% url 'sale:sale-detail' sale.id %}">{{ sale.date }}</a>
                </td>
            </tr>
        </table>
        {% endfor %}
    </div>

</div>

{% endblock %} 