api/urls.py
from django.urls import path 
from .views import (
    StaffListCreateAPIView, 
    StaffDetailAPIView, 
    StaffDestroyAPIView, 
    InventoryListCreateAPIView, 
    InventoryDetailAPIView, 
    InventoryDestroyAPIView, 
    SaleListCreateAPIView, 
    SaleDetailAPIView, 
    SaleDestroyAPIView, 
    JobListCreateAPIView, 
    JobDetailAPIView, 
    JobDestroyAPIView, 
    InventoryTypeListCreateAPIView, 
    InventoryTypeDetailAPIView, 
    InventoryTypeDestroyAPIView
)

app_name = 'api'
urlpatterns = [
    path('staff_list/', StaffListCreateAPIView.as_view()), 
    path('staff_detail/<int:pk>/', StaffDetailAPIView.as_view()), 
    path('staff_delete/<int:pk>/', StaffDestroyAPIView.as_view()), 

    path('inventory_list/', InventoryListCreateAPIView.as_view()), 
    path('inventory_detail/<int:pk>/', InventoryDetailAPIView.as_view()), 
    path('inventory_delete/<int:pk>/', InventoryDestroyAPIView.as_view()), 

    path('sale_list/', SaleListCreateAPIView.as_view()), 
    path('sale_detail/<int:pk>/', SaleDetailAPIView.as_view()), 
    path('sale_delete/<int:pk>/', SaleDestroyAPIView.as_view()), 
    
    path('job_list/', JobListCreateAPIView.as_view()), 
    path('job_detail/<int:pk>/', JobDetailAPIView.as_view()), 
    path('job_delete/<int:pk>/', JobDestroyAPIView.as_view()), 

    path('inv_type_list/', InventoryTypeListCreateAPIView.as_view()), 
    path('inv_type_detail/<int:pk>/', InventoryTypeDetailAPIView.as_view()), 
    path('inv_type_delete/<int:pk>/', InventoryTypeDestroyAPIView.as_view()), 

]

core/urls.py
from django.urls import path 
from django.conf import settings 
from django.conf.urls.static import static 
from .views import (
    homeView,
    reportView, 
    filterView, 
    reminderCreateView, 
    reminderHandleView, 
    helpView, 
)

app_name = 'core'
urlpatterns = [
    path('', homeView, name='home'), 
    path('report/', reportView, name='report'), 
    path('filter/', filterView, name='filter'), 
    path('reminders/', reminderCreateView, name='reminder'), 
    path('reminder-handle/', reminderHandleView, name='reminder-handle'), 
    path('help/', helpView, name='help'), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/urls.py
from django.urls import path 
from django.conf import settings 
from django.conf.urls.static import static 

from .views import (
    jobCreateView, 
    JobDeleteView, 
    JobDetailView, 
    JobListView, 
    JobUpdateView
)

app_name = 'job'
urlpatterns = [
    path('list/', JobListView.as_view(), name='job-list'), 
    path('<int:id>/', JobDetailView.as_view(), name='job-detail'), 
    path('<int:id>/delete/', JobDeleteView.as_view(), name='job-delete'), 
    path('create/', jobCreateView, name='job-create'), 
    path('<int:id>/update/', JobUpdateView.as_view(), name='job-update'),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

legend/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')), 
    path('core/', include('core.urls')), 
    path('staff/', include('staff.urls')), 
    path('inventory/', include('inventory.urls')), 
    path('job/', include('job.urls')), 
    path('sale/', include('sale.urls')), 
]

sale/urls.py
from django.urls import path 
from .views import (
    # SaleCreateView, 
    SaleDetailView, 
    SaleConfirmDeleteView, 
    SaleListView, 
    saleDelete, 
    saleCreateView, 
    saleDetailView, 
    saleUpdateView
)

app_name = 'sale'
urlpatterns = [
    path('list/', SaleListView.as_view(), name='sale-list'), 
    # path('<int:id>/', SaleDetailView.as_view(), name='sale-detail'),
    path('<int:id>/', saleDetailView, name='sale-detail'), 
    path('<int:id>delete/', saleDelete, name='sale-delete'), 
    path('<int:id>/confirm_delete/', SaleConfirmDeleteView.as_view(), name='sale-confirm-delete'), 
    # path('create/', SaleCreateView.as_view(), name='sale-create'), 
    path('create/', saleCreateView, name='sale-create'), 
    path('<int:id>/update/', saleUpdateView, name='sale-update')
]

staff/urls.py
from django.urls import path 
from django.conf import settings 
from django.conf.urls.static import static 
from .views import (
    staffCreateView, 
    StaffDeleteView, 
    StaffDetailView, 
    StaffListView, 
    StaffUpdateView,
    staffListView, 
)

app_name = 'staff'
urlpatterns = [
    path('list/', StaffListView.as_view(), name='staff-list'), 
    path('<int:pk>/', StaffDetailView.as_view(), name='staff-detail'), 
    # path('create/', StaffCreateView.as_view(), name='staff-create'), 
    path('create/', staffCreateView, name='staff-create'), 
    path('<int:pk>/update/', StaffUpdateView.as_view(), name='staff-update'), 
    path('<int:pk>/delete/', StaffDeleteView.as_view(), name='staff-delete')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff/models.py
from django.urls import reverse 
from django.db import models

# Create your models here.
class Staff(models.Model):
    name = models.CharField(max_length=120)
    state_of_origin = models.CharField(max_length=50)
    phone = models.CharField(max_length=11) 
    email = models.EmailField(max_length=50)
    home_residence = models.CharField(max_length=200)
    date_of_employment = models.DateField(auto_now=False)
    date_of_leave = models.DateField(auto_now=False) 
    active = models.BooleanField(default=False) 

    has_left = models.BooleanField(default=False) 
    is_employed = models.BooleanField(default=False) 

    def get_absolute_url(self):
        return reverse('staff:staff-detail', kwargs={'id': self.id})

    def __str__(self) -> str:
        return self.name 

staff/forms.py
from django import forms
from .models import Staff 

class StaffCreateForm(forms.ModelForm):
    name = forms.CharField(
                required=True, 
                widget=forms.TextInput(
                    attrs={
                        'class': 'form-control', 
                        'id': 'name', 
                        'placeholder': 'Name' 
                    }
                )
                ) 
    date_of_birth = forms.DateField(
                widget=forms.DateInput(
                    attrs={
                        'class': 'form-control',
                        'placeholder': 'Date of Birth'
                    }
                )
    )
    state_of_origin = forms.CharField(
                widget=forms.TextInput(
                    attrs={
                        'class': 'form-control', 
                        'id': 'state_of_origin', 
                        'placeholder': 'State of origin'
                    }
                )
    )
    phone = forms.CharField(
                widget=forms.TextInput(
                    attrs={
                        'class': 'form-control', 
                        'id': 'phone', 
                        'placeholder': 'Phone number'
                    }
                )
    )
    email = forms.EmailField(
                widget=forms.EmailInput(
                    attrs={
                        'class': 'form-control', 
                        'id': 'email', 
                        'placeholder': 'Email' 
                    }
                )
            )
    home_residence = forms.CharField(
                widget=forms.TextInput(
                    attrs={
                        'class': 'form-control', 
                        'id': 'home_residence', 
                        'placeholder': 'Home residence' 
                    }
                )
            )
    date_of_employment = forms.DateField(
                # label='Date employed', 
                widget=forms.DateInput(
                    attrs={
                        'class': 'form-control', 
                        'id': 'date_of_employment', 
                        'placeholder': 'Date of Employment'
                    }
                )
            )
    active = forms.BooleanField(
                # label='Is active',
                required=False,
                widget=forms.CheckboxInput(
                    attrs={
                        'id': 'date_of_employment', 
                    }
                )
            )
    
    class Meta: 
        model = Staff 
        fields = '__all__'

staff/views.py
from django.shortcuts import render, redirect
from django.views.generic import (
    CreateView, 
    DetailView, 
    ListView, 
    UpdateView, 
    DeleteView
)
from .models import Staff 
from .forms import StaffCreateForm

# Create your views here
class StaffListView(ListView):
    # model = Staff 
    template_name = 'staff/staff_list.html'
    queryset = Staff.objects.all() 

def staffListView(request):
    context = {
        'object_list': Staff.objects.all()
    }
    return render(request, 'staff/staff_list.html', context) 

class StaffDetailView(DetailView):
    template_name = 'staff/staff_detail.html' 
    queryset = Staff.objects.all()  # limits the list of objects to search in


class StaffDeleteView(DeleteView):
    template_name = 'staff/staff_delete.html' 
    success_url = '../../list/'

    def get_object(self):
        pk_ = self.kwargs.get('pk') 
        object = Staff.objects.get(pk=pk_) 
        return object 

def correctDateString(date_string):
    parts = date_string.split('-') 
    day = parts[0] 
    month = parts[1]
    year = parts[2]
    correct_date_string = '-'.join((day, month, year)) 
    return correct_date_string

def staffCreateView(request):
    ''' I couldn't use a normal CBV because I had to convert some of the 
    form data into other models in order to save them. 
    Update: I didn't then know how to use generic CBVs. Check out sale app '''
    template_name = 'staff/staff_create.html'

    if request.method == 'POST':
        default_date = '1800-08-08'
        data = {}
        data['name'] = request.POST.get('name')
        data['date_of_leave'] = request.POST.get('date_of_leave') or default_date
        if data['date_of_leave'] != default_date: 
            data['has_left'] = True 
        else: data['has_left'] = False 
        data['phone'] = request.POST.get('phone') 
        data['email'] = request.POST.get('email') 
        data['state_of_origin'] = request.POST.get('state_of_origin')
        data['home_residence'] = request.POST.get('home_residence') 
        data['date_of_employment'] = request.POST.get('date_of_employment') or default_date
        if data['date_of_employment'] != default_date: 
            data['is_employed'] = True 
        else: data['is_employed'] = False 
        data['active'] = True if request.POST.get('active')=='on' else False

        # # # print('Creating staff', data) 

        if data['name'] and data['phone']:
            instance = Staff(**data) 
            instance.save() 
            return redirect('../list/')
        else: 
            # # # # print('Unsuccessful submission') 
            context = {
                'object': object, 
                'no_good_error': '** Name and phone number are required **', 
            }
            return render(request, template_name, context)
        
    elif request.method == 'GET': 
        form = StaffCreateForm()
        all_staff = Staff.objects.all()
        context = {
            'form': form, 
            'all_staff': all_staff
        }
        return render(request, template_name, context)


class StaffUpdateView(UpdateView):
    template_name = 'staff/staff_update.html' 
    form_class = StaffCreateForm
    queryset = Staff.objects.all() 
    # success_url = '../../list/'

    def get_object(self):
        pk_ = self.kwargs.get('pk') 
        object = Staff.objects.get(pk=pk_) 
        return object 

    def get_context_data(self, **kwargs):
        object = self.get_object() 
        context = super().get_context_data(**kwargs)
        context['date_of_leave'] = str(object.date_of_leave)
        context['date_of_employment'] = str(object.date_of_employment)
        return context 

    def post(self, request, *args, **kwargs):
        # # # print(request.POST)
        default_date = '1800-08-08'
        object = self.get_object() 
        data = {}
        data['name'] = request.POST.get('name')
        data['date_of_leave'] = request.POST.get('date_of_leave') or default_date
        if data['date_of_leave'] != default_date: 
            data['has_left'] = True 
        else: 
            data['has_left'] = False 
        data['phone'] = request.POST.get('phone') 
        data['email'] = request.POST.get('email') 
        data['state_of_origin'] = request.POST.get('state_of_origin')
        data['home_residence'] = request.POST.get('home_residence') 
        data['date_of_employment'] = request.POST.get('date_of_employment') or default_date
        if data['date_of_employment'] != default_date: 
            data['is_employed'] = True 
        else: 
            data['is_employed'] = False 
        data['active'] = True if request.POST.get('active')=='on' else False

        if data['name'] and data['phone']:
            # # # print('Successful submission')
            # # # print(data)
            Staff.objects.filter(id=object.id).update(**data) 
            # # print('check 1')
            return redirect('../')

        else: 
            # # # print('Unsuccessful submission') 
            dob = str(object.date_of_leave)
            doe = str(object.date_of_employment) 
            context = {
                'object': object, 
                'no_good_error': '** Name and phone number are required **', 
                'date_of_leave': dob, 
                'date_of_employment': doe, 
            }
            return render(request, self.template_name, context)

    def get(self, request, *args,**kwargs):
        object = self.get_object() 
        dob = str(object.date_of_leave)
        doe = str(object.date_of_employment) 
        context = {
            'object': object, 
            'date_of_leave': dob, 
            'date_of_employment': doe, 
        }
        return render(request, self.template_name, context)

staff/templates/staff/base.html
{% load static %} 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Base{% endblock %}</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <style>
        a, .crimson, th {
            text-decoration: none;
            color: crimson;
        }
        a:hover {
            color: darkgreen;
        }
        .detail {
            font-size: large;
        }
        .label {
            font-weight: bold;
        }
    .footer>.row>.col>a {
        color: gray;
    }
    .footer>.row>.col>a:hover {
            color: rgb(11, 129, 129);
        }
    </style>
</head>
<body>
    {% block content %} 
        Base 
    {% endblock %} 

    <div class="footer">
        <div class="row row-cols-4 my-5 p-3 text-muted bg-dark text-center">
            <div class="col detail">
                <a href="{% url 'core:home' %}">Home</a>
            </div>
            <div class="col detail">
                <a href="{% url 'staff:staff-list' %}">Staff</a>
            </div>
            <div class="col detail">
                <a href="{% url 'inventory:inventory-list' %}">Inventory</a>
            </div>
            <div class="col detail">
                <a href="{% url 'sale:sale-list' %}">Sales</a>
            </div>
            <div class="col detail">
                <a href="{% url 'job:job-list' %}">Jobs</a>
            </div>
            <div class="col detail">
                <a href="{% url 'core:report' %}">Report</a>
            </div>
            <div class="col detail`">
                <a href="{% url 'core:reminder' %}">Reminders</a>
            </div>
            <div class="col detail">
                <a href="{% url 'core:help' %}">Help</a>
            </div>
        </div>
    </div>
</body>
</html>

staff/templates/staff/staff_create.html
{% extends 'staff/base.html' %} 

{% block title %}Register New Staff{% endblock %} 

{% block content %} 

<div class="container">
    <div class="row display-2 crimson">
        Register New Staff
    </div>
    <hr>
    <form action="{% url 'staff:staff-create' %}" method="post">{% csrf_token %}
        
        {% if no_good_error %}
        <div class="row detail text-danger">
            {{ no_good_error }}
        </div>
        {% endif %}

        <div class="row my-2">
            <input type="text" name="name" 
            class="form-control"
            placeholder="Name">
        </div>

        <div class="row my-2">
            <input type="text" 
            name="state_of_origin" 
            class="form-control" 
            placeholder="State of origin">
        </div>

        <div class="row my-2">
            <input type="text" 
            name="phone" 
            placeholder="Phone number"
            class="form-control">
        </div>

        <div class="row my-2">
            <input type="email" 
            name="email" 
            class="form-control" 
            placeholder="Email">
        </div>

        <div class="row my-2">
            <input type="text" 
            name="home_residence" 
            class="form-control" 
            placeholder="Home residence">
        </div>

        <div class="row my-2">
            <label for="date_of_employment">Date of employment</label>
            <input type="date" 
            name="date_of_employment" 
            class="form-control"
            placeholder="Date of Employment">
        </div>

        <div class="row my-2">
            <label for="date_of_leave">Date of Leaving</label>
            <input type="date" 
            name="date_of_leave" 
            class="form-control" >
        </div>

        <div class="row my-2 border p-2">
            <label for="active"><input type="checkbox" name="active" id="active"
            checked> Active</label>
            
        </div>

        <div class="row">
            <div class="col-5 mx-3 btn btn-secondary my-2 text-center py-3"><a class="text-white" href="../list/">Cancel</a></div>
            <div class="col-5 mx-3 btn btn-success my-2"><button type="submit" class="mx-auto btn text-white my-2">Add</button>
            </div>
        </div>

    </form>
</div>

{% endblock %}

staff/templates/staff/staff_delete.html
{% extends 'staff/base.html' %} 

{% block title %}Delete {{ object.name }}{% endblock %} 

{% block content %} 
<div class="container">
    <div class="row text-danger display-4">
        Confirm Delete
    </div>
    <div class="row detail">
        <p class="detail">Are you sure you want to delete this staff record?</p>
        <p class="text-primary display-4">{{ object.name }}</p>
        <div class="row">
            <div class="col mx-2 btn btn-secondary py-3">
                <a href="{% url 'staff:staff-detail' object.id %}"><span class="text-white">Cancel</span>
                </a>
            </div>

            <div class="col mx-2 text-white btn btn-danger">
                <form method="post" action="{% url 'staff:staff-delete' object.id %}">{% csrf_token %}
                    <button type="submit" class="btn btn-danger">Confirm</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %} 

staff/templates/staff/staff_detail.html
{% extends 'staff/base.html' %} 
{% load static %} 

{% block title %}{{ object.name }}{% endblock %} 

{% block content %} 
<div class="container">
    <div class="row">
        <div class="g-3 display-4 text-center text-danger">
            {{ object.name }} 
        </div>
    </div>
    <hr>
    <div class="row row-col-1 detail text-center">
        </div>
        <div class="col-12">
            <div class="row">
                <div class="col text-end"><span class="label">State of Origin:</span></div>
                <div class="col text-start">{{ object.state_of_origin }}</div>
            </div>
            
            
        </div>
        <div class="col-12">
            <div class="row">
                <div class="col text-end"><span class="label">Home Residence:</span></div>
                <div class="col text-start">{{ object.home_residence }}</div>
            </div>
            
            
        </div>
        <div class="col-12">
            <div class="row">
                <div class="col text-end"><span class="label">Phone Number:</span></div>
                <div class="col text-start">{{ object.phone }}</div>
            </div>

            
        </div>
        <div class="col-12">
            <div class="row">
                <div class="col text-end"><span class="label">Email Address:</span></div>
                <div class="col text-start">{{ object.email }}</div>
            </div>
            
            
        </div>
        <div class="col-12">
            <div class="row">
                <div class="col text-end"><span class="label">Date of Employment:</span></div>
                <div class="col text-start">
                    {% if object.is_employed %}
                    {{ object.date_of_employment }}
                    {% endif %}
                </div>
            </div>                       
        </div>

        {% if object.has_left %} 
        <div class="col-12">
            <div class="row">
                <div class="col text-end"><span class="label">Date of Leaving:</span></div>
                <div class="col text-start">{{ object.date_of_leave }}</div>
            </div>
        </div>
        {% endif %}

        <div class="col-12">
            <div class="row">
                <div class="col text-end"><span class="label">Active:</span></div>
                <div class="col text-start">{{ object.active }}</div>
            </div>
            
        </div>

    </div>

    <hr>
    <div class="row mx-auto">
        <div class="col-4 mx-2 btn btn-primary my-2 text-center py-3">
            <a class="text-white" href="{% url 'staff:staff-list' %}">Back</a>
        </div>
        <div class="col-3 mx-2 btn btn-primary my-2 py-3 text-center">
            <a class="text-white" href="{% url 'staff:staff-update' object.id %}">Update</a>
        </div>
        <div class="col-4 mx-2 btn btn-danger my-2 py-3 text-center">
            <a class="text-white" href="{% url 'staff:staff-delete' object.id %}">Delete</a>
        </div>
    </div>

</div>
{% endblock %}

staff/templates/staff/staff_list.html
{% extends './base.html' %} 

{% block title %}Staff List{% endblock %} 

{% block content %} 
<div class="container">

    <div class="row g-3">
        <div class="col display-1">All Staff</div>
        <div class="col mt-5"><a class="h4" href="{% url 'staff:staff-create' %}">Add New Staff</a></div>
        <div class="col mt-5"><a class="h4" href="{% url 'core:home' %}">Home</a></div>
    </div>

    <hr>

    <div class="staff my-3">
        {% for staff in object_list %} 
        <table class="table table-hover">
            <tr class="border border-3 rounded-2 my-2 py-3">
                <td class="display-5">
                    <a href="{% url 'staff:staff-detail' staff.id %}">{{ staff.name }}</a>
                </td>
                <td class="display-5 text-end">
                    {{ staff.phone }}
                </td>
            </tr>
        </table>
        {% endfor %}
    </div>

</div>
{% endblock %} 

staff/templates/staff/staff_update.html
{% extends 'staff/base.html' %} 

{% block title %}Update Staff{% endblock %} 

{% block content %} 

<div class="container">
    <div class="row display-2 crimson">
        Update This Staff
    </div>
    <hr>
    <form action="{% url 'staff:staff-update' object.id %}" method="post">{% csrf_token %}
        
        {% if no_good_error %}
        <div class="row detail text-danger">
            {{ no_good_error }}
        </div>
        {% endif %}

        <div class="row my-2">
            <input type="text" name="name" 
            class="form-control"
            placeholder="Name"
            value="{{ object.name }}">
        </div>


        <div class="row my-2">
            <input type="text" 
            name="state_of_origin" 
            class="form-control" 
            placeholder="State of origin"
            value="{{ object.state_of_origin }}">
        </div>

        <div class="row my-2">
            <input type="text" 
            name="phone" 
            placeholder="Phone number"
            class="form-control" 
            value="{{ object.phone }}">
        </div>

        <div class="row my-2">
            <input type="email" 
            name="email" 
            class="form-control" 
            placeholder="Email"
            value="{{ object.email }}">
        </div>

        <div class="row my-2">
            <input type="text" 
            name="home_residence" 
            class="form-control" 
            placeholder="Home residence"
            value="{{ object.home_residence}}">
        </div>

        <div class="row my-2">
            <label for="date_of_employment">Date of employment</label>
            <input type="date" 
            name="date_of_employment" 
            class="form-control"
            placeholder="Date of Employment"
            {% if object.is_employed %}value="{{ date_of_employment }}"{% endif %}>
        </div>

        <div class="row my-2">
            <label for="date_of_leave">Date of Leaving</label>
            <input type="date" 
            name="date_of_leave" 
            class="form-control" 
            {% if object.has_left %}value="{{ date_of_leave }}"{% endif %}>
        </div>

        <div class="row my-2 border p-2">
            <label for="active"><input type="checkbox" name="active" id="active"
            {% if object.active %}checked{% endif %}> Active</label>
            
        </div>

        <div class="row">
            <div class="col-5 mx-3 btn btn-secondary my-2 text-center py-3"><a class="text-white" href="../">Cancel</a></div>
            <div class="col-5 mx-3 btn btn-success my-2"><button type="submit" class="mx-auto btn text-white my-2">Save</button>
            </div>
        </div>

    </form>
</div>

{% endblock %}